eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: eureka_name_value_ksm
spring:
  cloud:
    config:
      override-system-properties: false

# for zipkin
management:
  tracing:
    sampling:
      probability: 1.0