server:
  port: 8050
spring:
  datasource:
    url: jdbc:mysql://docker:3306/product
    username: mysqluser
    password: mysqlpw
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none